In [35]:
import numpy as np
import pandas as pd

grid = []
path = '/home/shreyas_204/Downloads/sudoku.csv'


data = pd.read_csv(path, header = None)
for i in range(9):
    row = []
    for j in range(9):
        row.append(data[j][i])
    grid.append(row)

def checkRow(grid, x, row):
    return x not in grid[row]

def checkColumn(grid, x, column):
    for k in range(9):
        if x == grid[k][column]:
            return False
    return True


def checkGrid(grid, x, r, c):
    startrow = int(r / 3) * 3
    startcolumn = int(c / 3) * 3
    for i in range(startrow, startrow + 3):
        for j in range(startcolumn, startcolumn + 3):
            if x == grid[i][j]:
                return False
    return True

def sudoku():
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                for x in range(1, 10):
                    a = checkRow(grid, x, i)
                    b = checkColumn(grid, x, j)
                    c = checkGrid(grid, x, i, j)
                    if a and b and c:
                        grid[i][j] = x
                        sudoku()
                        grid[i][j] = 0
                return
    print(np.matrix(grid))

In [36]:
sudoku()

[[7 4 8 6 9 3 1 2 5]
 [6 3 1 5 8 2 9 4 7]
 [5 2 9 4 7 1 3 6 8]
 [1 9 5 2 3 4 8 7 6]
 [8 6 2 1 5 7 4 9 3]
 [4 7 3 8 6 9 5 1 2]
 [3 1 7 9 2 5 6 8 4]
 [2 8 4 3 1 6 7 5 9]
 [9 5 6 7 4 8 2 3 1]]
